
desc 'test out ideas here'

namespace :white_board do
  task test_ideas: :environment do
    require 'httparty'

    user_agent = "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Mobile Safari/537.36"

    address = '1610 Pennsylvania Ave'
    city = 'Saint Louis Park'
    lat_long_obj = LatLongFromAddress.find_or_create_by(address: address, city: city)
    lat_long_obj.populate unless lat_long_obj.previously_looked_up

    lat = lat_long_obj.lat.to_f.round(4).to_s
    long = lat_long_obj.long.to_f.round(4).to_s

    puts "The lat:#{lat} long:#{long} of #{address} #{city}"

    uri = URI.parse("https://api.weather.gov/points/#{lat},#{long}")
    response = Net::HTTP.get(uri)
    json_resp = JSON.parse(response)
    uri_forecast = json_resp['properties']['forecast']
    uri_forecast_hourly = json_resp['properties']['forecastHourly']

    page = HTTParty.get(uri_forecast)
    json_resp = JSON.parse(page)
    pp json_resp
  end
end



# @context
# id
# type
# geometry
# properties

# {"@context"=>
#   ["https://geojson.org/geojson-ld/geojson-context.jsonld",
#    {"@version"=>"1.1",
#     "wx"=>"https://api.weather.gov/ontology#",
#     "s"=>"https://schema.org/",
#     "geo"=>"http://www.opengis.net/ont/geosparql#",
#     "unit"=>"http://codes.wmo.int/common/unit/",
#     "@vocab"=>"https://api.weather.gov/ontology#",
#     "geometry"=>{"@id"=>"s:GeoCoordinates", "@type"=>"geo:wktLiteral"},
#     "city"=>"s:addressLocality",
#     "state"=>"s:addressRegion",
#     "distance"=>{"@id"=>"s:Distance", "@type"=>"s:QuantitativeValue"},
#     "bearing"=>{"@type"=>"s:QuantitativeValue"},
#     "value"=>{"@id"=>"s:value"},
#     "unitCode"=>{"@id"=>"s:unitCode", "@type"=>"@id"},
#     "forecastOffice"=>{"@type"=>"@id"},
#     "forecastGridData"=>{"@type"=>"@id"},
#     "publicZone"=>{"@type"=>"@id"},
#     "county"=>{"@type"=>"@id"}}],
#  "id"=>"https://api.weather.gov/points/44.9673,-93.3763",
#  "type"=>"Feature",
#  "geometry"=>{"type"=>"Point", "coordinates"=>[-93.3763, 44.9673]},
#  "properties"=>
#   {"@id"=>"https://api.weather.gov/points/44.9673,-93.3763",
#    "@type"=>"wx:Point",
#    "cwa"=>"MPX",
#    "forecastOffice"=>"https://api.weather.gov/offices/MPX",
#    "gridId"=>"MPX",
#    "gridX"=>104,
#    "gridY"=>71,
#    "forecast"=>"https://api.weather.gov/gridpoints/MPX/104,71/forecast",
#    "forecastHourly"=>
#     "https://api.weather.gov/gridpoints/MPX/104,71/forecast/hourly",
#    "forecastGridData"=>"https://api.weather.gov/gridpoints/MPX/104,71",
#    "observationStations"=>
#     "https://api.weather.gov/gridpoints/MPX/104,71/stations",
#    "relativeLocation"=>
#     {"type"=>"Feature",
#      "geometry"=>{"type"=>"Point", "coordinates"=>[-93.365035, 44.948681]},
#      "properties"=>
#       {"city"=>"St. Louis Park",
#        "state"=>"MN",
#        "distance"=>{"unitCode"=>"wmoUnit:m", "value"=>2252.1062431656},
#        "bearing"=>{"unitCode"=>"wmoUnit:degree_(angle)", "value"=>336}}},
#    "forecastZone"=>"https://api.weather.gov/zones/forecast/MNZ060",
#    "county"=>"https://api.weather.gov/zones/county/MNC053",
#    "fireWeatherZone"=>"https://api.weather.gov/zones/fire/MNZ060",
#    "timeZone"=>"America/Chicago",
#    "radarStation"=>"KMPX"}}

# HOURLY FORECAST
# % rake white_board:test_ideas
# The lat:44.9673 long:-93.3763 of 1610 Pennsylvania Ave Saint Louis Park
# {"@context"=>
#   ["https://geojson.org/geojson-ld/geojson-context.jsonld",
#    {"@version"=>"1.1",
#     "wx"=>"https://api.weather.gov/ontology#",
#     "geo"=>"http://www.opengis.net/ont/geosparql#",
#     "unit"=>"http://codes.wmo.int/common/unit/",
#     "@vocab"=>"https://api.weather.gov/ontology#"}],
#  "type"=>"Feature",
#  "geometry"=>
#   {"type"=>"Polygon",
#    "coordinates"=>
#     [[[-93.3832362, 44.9877149],
#       [-93.3835967, 44.9663311],
#       [-93.3533824, 44.9660738],
#       [-93.3530152, 44.9874576],
#       [-93.3832362, 44.9877149]]]},
#  "properties"=>
#   {"updated"=>"2021-12-17T15:15:13+00:00",
#    "units"=>"us",
#    "forecastGenerator"=>"HourlyForecastGenerator",
#    "generatedAt"=>"2021-12-17T19:04:40+00:00",
#    "updateTime"=>"2021-12-17T15:15:13+00:00",
#    "validTimes"=>"2021-12-17T09:00:00+00:00/P7DT16H",
#    "elevation"=>{"unitCode"=>"wmoUnit:m", "value"=>274.0152},
#    "periods"=>
#     [{"number"=>1,
#       "name"=>"",
#       "startTime"=>"2021-12-17T13:00:00-06:00",
#       "endTime"=>"2021-12-17T14:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>19,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"E",
#       "icon"=>"https://api.weather.gov/icons/land/day/ovc?size=small",
#       "shortForecast"=>"Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>2,
#       "name"=>"",
#       "startTime"=>"2021-12-17T14:00:00-06:00",
#       "endTime"=>"2021-12-17T15:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>20,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"ENE",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>3,
#       "name"=>"",
#       "startTime"=>"2021-12-17T15:00:00-06:00",
#       "endTime"=>"2021-12-17T16:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>21,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"ENE",
#       "icon"=>"https://api.weather.gov/icons/land/day/ovc?size=small",
#       "shortForecast"=>"Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>4,
#       "name"=>"",
#       "startTime"=>"2021-12-17T16:00:00-06:00",
#       "endTime"=>"2021-12-17T17:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>21,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"ENE",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>5,
#       "name"=>"",
#       "startTime"=>"2021-12-17T17:00:00-06:00",
#       "endTime"=>"2021-12-17T18:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>20,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"ENE",
#       "icon"=>"https://api.weather.gov/icons/land/day/ovc?size=small",
#       "shortForecast"=>"Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>6,
#       "name"=>"",
#       "startTime"=>"2021-12-17T18:00:00-06:00",
#       "endTime"=>"2021-12-17T19:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>20,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"ENE",
#       "icon"=>"https://api.weather.gov/icons/land/night/ovc?size=small",
#       "shortForecast"=>"Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>7,
#       "name"=>"",
#       "startTime"=>"2021-12-17T19:00:00-06:00",
#       "endTime"=>"2021-12-17T20:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>20,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"ENE",
#       "icon"=>"https://api.weather.gov/icons/land/night/ovc?size=small",
#       "shortForecast"=>"Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>8,
#       "name"=>"",
#       "startTime"=>"2021-12-17T20:00:00-06:00",
#       "endTime"=>"2021-12-17T21:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>20,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"ENE",
#       "icon"=>"https://api.weather.gov/icons/land/night/ovc?size=small",
#       "shortForecast"=>"Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>9,
#       "name"=>"",
#       "startTime"=>"2021-12-17T21:00:00-06:00",
#       "endTime"=>"2021-12-17T22:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>20,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"NE",
#       "icon"=>"https://api.weather.gov/icons/land/night/ovc?size=small",
#       "shortForecast"=>"Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>10,
#       "name"=>"",
#       "startTime"=>"2021-12-17T22:00:00-06:00",
#       "endTime"=>"2021-12-17T23:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>20,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"NE",
#       "icon"=>"https://api.weather.gov/icons/land/night/ovc?size=small",
#       "shortForecast"=>"Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>11,
#       "name"=>"",
#       "startTime"=>"2021-12-17T23:00:00-06:00",
#       "endTime"=>"2021-12-18T00:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>19,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"NE",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>12,
#       "name"=>"",
#       "startTime"=>"2021-12-18T00:00:00-06:00",
#       "endTime"=>"2021-12-18T01:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>19,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"NE",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>13,
#       "name"=>"",
#       "startTime"=>"2021-12-18T01:00:00-06:00",
#       "endTime"=>"2021-12-18T02:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>19,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"NE",
#       "icon"=>"https://api.weather.gov/icons/land/night/snow,20?size=small",
#       "shortForecast"=>"Slight Chance Light Snow",
#       "detailedForecast"=>""},
#      {"number"=>14,
#       "name"=>"",
#       "startTime"=>"2021-12-18T02:00:00-06:00",
#       "endTime"=>"2021-12-18T03:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>19,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"NE",
#       "icon"=>"https://api.weather.gov/icons/land/night/snow,20?size=small",
#       "shortForecast"=>"Slight Chance Light Snow",
#       "detailedForecast"=>""},
#      {"number"=>15,
#       "name"=>"",
#       "startTime"=>"2021-12-18T03:00:00-06:00",
#       "endTime"=>"2021-12-18T04:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>19,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"NNE",
#       "icon"=>"https://api.weather.gov/icons/land/night/snow,20?size=small",
#       "shortForecast"=>"Slight Chance Light Snow",
#       "detailedForecast"=>""},
#      {"number"=>16,
#       "name"=>"",
#       "startTime"=>"2021-12-18T04:00:00-06:00",
#       "endTime"=>"2021-12-18T05:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>18,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"N",
#       "icon"=>"https://api.weather.gov/icons/land/night/snow?size=small",
#       "shortForecast"=>"Slight Chance Light Snow",
#       "detailedForecast"=>""},
#      {"number"=>17,
#       "name"=>"",
#       "startTime"=>"2021-12-18T05:00:00-06:00",
#       "endTime"=>"2021-12-18T06:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>18,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"N",
#       "icon"=>"https://api.weather.gov/icons/land/night/snow?size=small",
#       "shortForecast"=>"Chance Light Snow",
#       "detailedForecast"=>""},
#      {"number"=>18,
#       "name"=>"",
#       "startTime"=>"2021-12-18T06:00:00-06:00",
#       "endTime"=>"2021-12-18T07:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>17,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"NNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/snow?size=small",
#       "shortForecast"=>"Slight Chance Light Snow",
#       "detailedForecast"=>""},
#      {"number"=>19,
#       "name"=>"",
#       "startTime"=>"2021-12-18T07:00:00-06:00",
#       "endTime"=>"2021-12-18T08:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>17,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"NNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/snow?size=small",
#       "shortForecast"=>"Slight Chance Light Snow",
#       "detailedForecast"=>""},
#      {"number"=>20,
#       "name"=>"",
#       "startTime"=>"2021-12-18T08:00:00-06:00",
#       "endTime"=>"2021-12-18T09:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>17,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"NNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/snow?size=small",
#       "shortForecast"=>"Slight Chance Light Snow",
#       "detailedForecast"=>""},
#      {"number"=>21,
#       "name"=>"",
#       "startTime"=>"2021-12-18T09:00:00-06:00",
#       "endTime"=>"2021-12-18T10:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>18,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"NNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/ovc?size=small",
#       "shortForecast"=>"Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>22,
#       "name"=>"",
#       "startTime"=>"2021-12-18T10:00:00-06:00",
#       "endTime"=>"2021-12-18T11:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>18,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"NNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>23,
#       "name"=>"",
#       "startTime"=>"2021-12-18T11:00:00-06:00",
#       "endTime"=>"2021-12-18T12:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>18,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>24,
#       "name"=>"",
#       "startTime"=>"2021-12-18T12:00:00-06:00",
#       "endTime"=>"2021-12-18T13:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>18,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>25,
#       "name"=>"",
#       "startTime"=>"2021-12-18T13:00:00-06:00",
#       "endTime"=>"2021-12-18T14:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>18,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>26,
#       "name"=>"",
#       "startTime"=>"2021-12-18T14:00:00-06:00",
#       "endTime"=>"2021-12-18T15:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>19,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>27,
#       "name"=>"",
#       "startTime"=>"2021-12-18T15:00:00-06:00",
#       "endTime"=>"2021-12-18T16:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>19,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>28,
#       "name"=>"",
#       "startTime"=>"2021-12-18T16:00:00-06:00",
#       "endTime"=>"2021-12-18T17:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>18,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>29,
#       "name"=>"",
#       "startTime"=>"2021-12-18T17:00:00-06:00",
#       "endTime"=>"2021-12-18T18:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>16,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>30,
#       "name"=>"",
#       "startTime"=>"2021-12-18T18:00:00-06:00",
#       "endTime"=>"2021-12-18T19:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>15,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>31,
#       "name"=>"",
#       "startTime"=>"2021-12-18T19:00:00-06:00",
#       "endTime"=>"2021-12-18T20:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>14,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>32,
#       "name"=>"",
#       "startTime"=>"2021-12-18T20:00:00-06:00",
#       "endTime"=>"2021-12-18T21:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>13,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>33,
#       "name"=>"",
#       "startTime"=>"2021-12-18T21:00:00-06:00",
#       "endTime"=>"2021-12-18T22:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>12,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>34,
#       "name"=>"",
#       "startTime"=>"2021-12-18T22:00:00-06:00",
#       "endTime"=>"2021-12-18T23:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>11,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>35,
#       "name"=>"",
#       "startTime"=>"2021-12-18T23:00:00-06:00",
#       "endTime"=>"2021-12-19T00:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>11,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"W",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>36,
#       "name"=>"",
#       "startTime"=>"2021-12-19T00:00:00-06:00",
#       "endTime"=>"2021-12-19T01:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>10,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"W",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>37,
#       "name"=>"",
#       "startTime"=>"2021-12-19T01:00:00-06:00",
#       "endTime"=>"2021-12-19T02:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>10,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"0 mph",
#       "windDirection"=>"W",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>38,
#       "name"=>"",
#       "startTime"=>"2021-12-19T02:00:00-06:00",
#       "endTime"=>"2021-12-19T03:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>9,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"0 mph",
#       "windDirection"=>"SW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>39,
#       "name"=>"",
#       "startTime"=>"2021-12-19T03:00:00-06:00",
#       "endTime"=>"2021-12-19T04:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>9,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"0 mph",
#       "windDirection"=>"SW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>40,
#       "name"=>"",
#       "startTime"=>"2021-12-19T04:00:00-06:00",
#       "endTime"=>"2021-12-19T05:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>9,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"SSW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>41,
#       "name"=>"",
#       "startTime"=>"2021-12-19T05:00:00-06:00",
#       "endTime"=>"2021-12-19T06:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>9,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"S",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>42,
#       "name"=>"",
#       "startTime"=>"2021-12-19T06:00:00-06:00",
#       "endTime"=>"2021-12-19T07:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>9,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"S",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>43,
#       "name"=>"",
#       "startTime"=>"2021-12-19T07:00:00-06:00",
#       "endTime"=>"2021-12-19T08:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>10,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"S",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>44,
#       "name"=>"",
#       "startTime"=>"2021-12-19T08:00:00-06:00",
#       "endTime"=>"2021-12-19T09:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>11,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"S",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>45,
#       "name"=>"",
#       "startTime"=>"2021-12-19T09:00:00-06:00",
#       "endTime"=>"2021-12-19T10:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>13,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"S",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>46,
#       "name"=>"",
#       "startTime"=>"2021-12-19T10:00:00-06:00",
#       "endTime"=>"2021-12-19T11:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>16,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"S",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>47,
#       "name"=>"",
#       "startTime"=>"2021-12-19T11:00:00-06:00",
#       "endTime"=>"2021-12-19T12:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>18,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"15 mph",
#       "windDirection"=>"S",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>48,
#       "name"=>"",
#       "startTime"=>"2021-12-19T12:00:00-06:00",
#       "endTime"=>"2021-12-19T13:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>21,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"15 mph",
#       "windDirection"=>"S",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>49,
#       "name"=>"",
#       "startTime"=>"2021-12-19T13:00:00-06:00",
#       "endTime"=>"2021-12-19T14:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>23,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"15 mph",
#       "windDirection"=>"S",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>50,
#       "name"=>"",
#       "startTime"=>"2021-12-19T14:00:00-06:00",
#       "endTime"=>"2021-12-19T15:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>25,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"15 mph",
#       "windDirection"=>"S",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>51,
#       "name"=>"",
#       "startTime"=>"2021-12-19T15:00:00-06:00",
#       "endTime"=>"2021-12-19T16:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>26,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"15 mph",
#       "windDirection"=>"S",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>52,
#       "name"=>"",
#       "startTime"=>"2021-12-19T16:00:00-06:00",
#       "endTime"=>"2021-12-19T17:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>27,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"S",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>53,
#       "name"=>"",
#       "startTime"=>"2021-12-19T17:00:00-06:00",
#       "endTime"=>"2021-12-19T18:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>27,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"S",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>54,
#       "name"=>"",
#       "startTime"=>"2021-12-19T18:00:00-06:00",
#       "endTime"=>"2021-12-19T19:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>27,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"S",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>55,
#       "name"=>"",
#       "startTime"=>"2021-12-19T19:00:00-06:00",
#       "endTime"=>"2021-12-19T20:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>27,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"S",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>56,
#       "name"=>"",
#       "startTime"=>"2021-12-19T20:00:00-06:00",
#       "endTime"=>"2021-12-19T21:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>27,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"SSW",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>57,
#       "name"=>"",
#       "startTime"=>"2021-12-19T21:00:00-06:00",
#       "endTime"=>"2021-12-19T22:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>27,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"SSW",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>58,
#       "name"=>"",
#       "startTime"=>"2021-12-19T22:00:00-06:00",
#       "endTime"=>"2021-12-19T23:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>27,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"SSW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>59,
#       "name"=>"",
#       "startTime"=>"2021-12-19T23:00:00-06:00",
#       "endTime"=>"2021-12-20T00:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>27,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"SSW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>60,
#       "name"=>"",
#       "startTime"=>"2021-12-20T00:00:00-06:00",
#       "endTime"=>"2021-12-20T01:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>27,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"SSW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>61,
#       "name"=>"",
#       "startTime"=>"2021-12-20T01:00:00-06:00",
#       "endTime"=>"2021-12-20T02:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>27,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"SW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>62,
#       "name"=>"",
#       "startTime"=>"2021-12-20T02:00:00-06:00",
#       "endTime"=>"2021-12-20T03:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>27,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"SW",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>63,
#       "name"=>"",
#       "startTime"=>"2021-12-20T03:00:00-06:00",
#       "endTime"=>"2021-12-20T04:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>26,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"WSW",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>64,
#       "name"=>"",
#       "startTime"=>"2021-12-20T04:00:00-06:00",
#       "endTime"=>"2021-12-20T05:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>25,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"WSW",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>65,
#       "name"=>"",
#       "startTime"=>"2021-12-20T05:00:00-06:00",
#       "endTime"=>"2021-12-20T06:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>24,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"W",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>66,
#       "name"=>"",
#       "startTime"=>"2021-12-20T06:00:00-06:00",
#       "endTime"=>"2021-12-20T07:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>23,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"W",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>67,
#       "name"=>"",
#       "startTime"=>"2021-12-20T07:00:00-06:00",
#       "endTime"=>"2021-12-20T08:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>22,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>68,
#       "name"=>"",
#       "startTime"=>"2021-12-20T08:00:00-06:00",
#       "endTime"=>"2021-12-20T09:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>22,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>69,
#       "name"=>"",
#       "startTime"=>"2021-12-20T09:00:00-06:00",
#       "endTime"=>"2021-12-20T10:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>22,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>70,
#       "name"=>"",
#       "startTime"=>"2021-12-20T10:00:00-06:00",
#       "endTime"=>"2021-12-20T11:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>22,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>71,
#       "name"=>"",
#       "startTime"=>"2021-12-20T11:00:00-06:00",
#       "endTime"=>"2021-12-20T12:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>23,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>72,
#       "name"=>"",
#       "startTime"=>"2021-12-20T12:00:00-06:00",
#       "endTime"=>"2021-12-20T13:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>23,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>73,
#       "name"=>"",
#       "startTime"=>"2021-12-20T13:00:00-06:00",
#       "endTime"=>"2021-12-20T14:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>23,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>74,
#       "name"=>"",
#       "startTime"=>"2021-12-20T14:00:00-06:00",
#       "endTime"=>"2021-12-20T15:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>23,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>75,
#       "name"=>"",
#       "startTime"=>"2021-12-20T15:00:00-06:00",
#       "endTime"=>"2021-12-20T16:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>23,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>76,
#       "name"=>"",
#       "startTime"=>"2021-12-20T16:00:00-06:00",
#       "endTime"=>"2021-12-20T17:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>22,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>77,
#       "name"=>"",
#       "startTime"=>"2021-12-20T17:00:00-06:00",
#       "endTime"=>"2021-12-20T18:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>20,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>78,
#       "name"=>"",
#       "startTime"=>"2021-12-20T18:00:00-06:00",
#       "endTime"=>"2021-12-20T19:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>18,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>79,
#       "name"=>"",
#       "startTime"=>"2021-12-20T19:00:00-06:00",
#       "endTime"=>"2021-12-20T20:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>17,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/night/few?size=small",
#       "shortForecast"=>"Mostly Clear",
#       "detailedForecast"=>""},
#      {"number"=>80,
#       "name"=>"",
#       "startTime"=>"2021-12-20T20:00:00-06:00",
#       "endTime"=>"2021-12-20T21:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>15,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/night/few?size=small",
#       "shortForecast"=>"Mostly Clear",
#       "detailedForecast"=>""},
#      {"number"=>81,
#       "name"=>"",
#       "startTime"=>"2021-12-20T21:00:00-06:00",
#       "endTime"=>"2021-12-20T22:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>14,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/night/few?size=small",
#       "shortForecast"=>"Mostly Clear",
#       "detailedForecast"=>""},
#      {"number"=>82,
#       "name"=>"",
#       "startTime"=>"2021-12-20T22:00:00-06:00",
#       "endTime"=>"2021-12-20T23:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>13,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/night/few?size=small",
#       "shortForecast"=>"Mostly Clear",
#       "detailedForecast"=>""},
#      {"number"=>83,
#       "name"=>"",
#       "startTime"=>"2021-12-20T23:00:00-06:00",
#       "endTime"=>"2021-12-21T00:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>11,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/night/few?size=small",
#       "shortForecast"=>"Mostly Clear",
#       "detailedForecast"=>""},
#      {"number"=>84,
#       "name"=>"",
#       "startTime"=>"2021-12-21T00:00:00-06:00",
#       "endTime"=>"2021-12-21T01:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>10,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/night/few?size=small",
#       "shortForecast"=>"Mostly Clear",
#       "detailedForecast"=>""},
#      {"number"=>85,
#       "name"=>"",
#       "startTime"=>"2021-12-21T01:00:00-06:00",
#       "endTime"=>"2021-12-21T02:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>9,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>86,
#       "name"=>"",
#       "startTime"=>"2021-12-21T02:00:00-06:00",
#       "endTime"=>"2021-12-21T03:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>8,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>87,
#       "name"=>"",
#       "startTime"=>"2021-12-21T03:00:00-06:00",
#       "endTime"=>"2021-12-21T04:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>7,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>88,
#       "name"=>"",
#       "startTime"=>"2021-12-21T04:00:00-06:00",
#       "endTime"=>"2021-12-21T05:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>6,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>89,
#       "name"=>"",
#       "startTime"=>"2021-12-21T05:00:00-06:00",
#       "endTime"=>"2021-12-21T06:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>6,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>90,
#       "name"=>"",
#       "startTime"=>"2021-12-21T06:00:00-06:00",
#       "endTime"=>"2021-12-21T07:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>6,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>91,
#       "name"=>"",
#       "startTime"=>"2021-12-21T07:00:00-06:00",
#       "endTime"=>"2021-12-21T08:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>6,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>92,
#       "name"=>"",
#       "startTime"=>"2021-12-21T08:00:00-06:00",
#       "endTime"=>"2021-12-21T09:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>7,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"W",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>93,
#       "name"=>"",
#       "startTime"=>"2021-12-21T09:00:00-06:00",
#       "endTime"=>"2021-12-21T10:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>8,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WSW",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>94,
#       "name"=>"",
#       "startTime"=>"2021-12-21T10:00:00-06:00",
#       "endTime"=>"2021-12-21T11:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>10,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WSW",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>95,
#       "name"=>"",
#       "startTime"=>"2021-12-21T11:00:00-06:00",
#       "endTime"=>"2021-12-21T12:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>12,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"SSW",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>96,
#       "name"=>"",
#       "startTime"=>"2021-12-21T12:00:00-06:00",
#       "endTime"=>"2021-12-21T13:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>14,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"S",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>97,
#       "name"=>"",
#       "startTime"=>"2021-12-21T13:00:00-06:00",
#       "endTime"=>"2021-12-21T14:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>16,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"S",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>98,
#       "name"=>"",
#       "startTime"=>"2021-12-21T14:00:00-06:00",
#       "endTime"=>"2021-12-21T15:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>17,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"S",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>99,
#       "name"=>"",
#       "startTime"=>"2021-12-21T15:00:00-06:00",
#       "endTime"=>"2021-12-21T16:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>18,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"S",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>100,
#       "name"=>"",
#       "startTime"=>"2021-12-21T16:00:00-06:00",
#       "endTime"=>"2021-12-21T17:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>18,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"S",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>101,
#       "name"=>"",
#       "startTime"=>"2021-12-21T17:00:00-06:00",
#       "endTime"=>"2021-12-21T18:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>17,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"SSW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>102,
#       "name"=>"",
#       "startTime"=>"2021-12-21T18:00:00-06:00",
#       "endTime"=>"2021-12-21T19:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>16,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"SSW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>103,
#       "name"=>"",
#       "startTime"=>"2021-12-21T19:00:00-06:00",
#       "endTime"=>"2021-12-21T20:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>16,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"SSW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>104,
#       "name"=>"",
#       "startTime"=>"2021-12-21T20:00:00-06:00",
#       "endTime"=>"2021-12-21T21:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>16,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"SW",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>105,
#       "name"=>"",
#       "startTime"=>"2021-12-21T21:00:00-06:00",
#       "endTime"=>"2021-12-21T22:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>16,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"SW",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>106,
#       "name"=>"",
#       "startTime"=>"2021-12-21T22:00:00-06:00",
#       "endTime"=>"2021-12-21T23:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>16,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"SW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>107,
#       "name"=>"",
#       "startTime"=>"2021-12-21T23:00:00-06:00",
#       "endTime"=>"2021-12-22T00:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>15,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WSW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>108,
#       "name"=>"",
#       "startTime"=>"2021-12-22T00:00:00-06:00",
#       "endTime"=>"2021-12-22T01:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>15,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WSW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>109,
#       "name"=>"",
#       "startTime"=>"2021-12-22T01:00:00-06:00",
#       "endTime"=>"2021-12-22T02:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>15,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WSW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>110,
#       "name"=>"",
#       "startTime"=>"2021-12-22T02:00:00-06:00",
#       "endTime"=>"2021-12-22T03:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>14,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"W",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>111,
#       "name"=>"",
#       "startTime"=>"2021-12-22T03:00:00-06:00",
#       "endTime"=>"2021-12-22T04:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>14,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"W",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>112,
#       "name"=>"",
#       "startTime"=>"2021-12-22T04:00:00-06:00",
#       "endTime"=>"2021-12-22T05:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>13,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"W",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>113,
#       "name"=>"",
#       "startTime"=>"2021-12-22T05:00:00-06:00",
#       "endTime"=>"2021-12-22T06:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>12,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>114,
#       "name"=>"",
#       "startTime"=>"2021-12-22T06:00:00-06:00",
#       "endTime"=>"2021-12-22T07:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>12,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>115,
#       "name"=>"",
#       "startTime"=>"2021-12-22T07:00:00-06:00",
#       "endTime"=>"2021-12-22T08:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>12,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>116,
#       "name"=>"",
#       "startTime"=>"2021-12-22T08:00:00-06:00",
#       "endTime"=>"2021-12-22T09:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>13,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>117,
#       "name"=>"",
#       "startTime"=>"2021-12-22T09:00:00-06:00",
#       "endTime"=>"2021-12-22T10:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>14,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>118,
#       "name"=>"",
#       "startTime"=>"2021-12-22T10:00:00-06:00",
#       "endTime"=>"2021-12-22T11:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>16,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>119,
#       "name"=>"",
#       "startTime"=>"2021-12-22T11:00:00-06:00",
#       "endTime"=>"2021-12-22T12:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>18,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>120,
#       "name"=>"",
#       "startTime"=>"2021-12-22T12:00:00-06:00",
#       "endTime"=>"2021-12-22T13:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>20,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>121,
#       "name"=>"",
#       "startTime"=>"2021-12-22T13:00:00-06:00",
#       "endTime"=>"2021-12-22T14:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>21,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>122,
#       "name"=>"",
#       "startTime"=>"2021-12-22T14:00:00-06:00",
#       "endTime"=>"2021-12-22T15:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>21,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>123,
#       "name"=>"",
#       "startTime"=>"2021-12-22T15:00:00-06:00",
#       "endTime"=>"2021-12-22T16:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>21,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>124,
#       "name"=>"",
#       "startTime"=>"2021-12-22T16:00:00-06:00",
#       "endTime"=>"2021-12-22T17:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>21,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>125,
#       "name"=>"",
#       "startTime"=>"2021-12-22T17:00:00-06:00",
#       "endTime"=>"2021-12-22T18:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>20,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=small",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>126,
#       "name"=>"",
#       "startTime"=>"2021-12-22T18:00:00-06:00",
#       "endTime"=>"2021-12-22T19:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>19,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>127,
#       "name"=>"",
#       "startTime"=>"2021-12-22T19:00:00-06:00",
#       "endTime"=>"2021-12-22T20:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>18,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>128,
#       "name"=>"",
#       "startTime"=>"2021-12-22T20:00:00-06:00",
#       "endTime"=>"2021-12-22T21:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>17,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"W",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>129,
#       "name"=>"",
#       "startTime"=>"2021-12-22T21:00:00-06:00",
#       "endTime"=>"2021-12-22T22:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>16,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"W",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>130,
#       "name"=>"",
#       "startTime"=>"2021-12-22T22:00:00-06:00",
#       "endTime"=>"2021-12-22T23:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>15,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"W",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>131,
#       "name"=>"",
#       "startTime"=>"2021-12-22T23:00:00-06:00",
#       "endTime"=>"2021-12-23T00:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>15,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"W",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>132,
#       "name"=>"",
#       "startTime"=>"2021-12-23T00:00:00-06:00",
#       "endTime"=>"2021-12-23T01:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>15,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"W",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>133,
#       "name"=>"",
#       "startTime"=>"2021-12-23T01:00:00-06:00",
#       "endTime"=>"2021-12-23T02:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>15,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>134,
#       "name"=>"",
#       "startTime"=>"2021-12-23T02:00:00-06:00",
#       "endTime"=>"2021-12-23T03:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>15,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>135,
#       "name"=>"",
#       "startTime"=>"2021-12-23T03:00:00-06:00",
#       "endTime"=>"2021-12-23T04:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>15,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>136,
#       "name"=>"",
#       "startTime"=>"2021-12-23T04:00:00-06:00",
#       "endTime"=>"2021-12-23T05:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>15,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>137,
#       "name"=>"",
#       "startTime"=>"2021-12-23T05:00:00-06:00",
#       "endTime"=>"2021-12-23T06:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>14,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>138,
#       "name"=>"",
#       "startTime"=>"2021-12-23T06:00:00-06:00",
#       "endTime"=>"2021-12-23T07:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>14,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>139,
#       "name"=>"",
#       "startTime"=>"2021-12-23T07:00:00-06:00",
#       "endTime"=>"2021-12-23T08:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>14,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>140,
#       "name"=>"",
#       "startTime"=>"2021-12-23T08:00:00-06:00",
#       "endTime"=>"2021-12-23T09:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>14,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>141,
#       "name"=>"",
#       "startTime"=>"2021-12-23T09:00:00-06:00",
#       "endTime"=>"2021-12-23T10:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>15,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>142,
#       "name"=>"",
#       "startTime"=>"2021-12-23T10:00:00-06:00",
#       "endTime"=>"2021-12-23T11:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>17,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>143,
#       "name"=>"",
#       "startTime"=>"2021-12-23T11:00:00-06:00",
#       "endTime"=>"2021-12-23T12:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>18,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>144,
#       "name"=>"",
#       "startTime"=>"2021-12-23T12:00:00-06:00",
#       "endTime"=>"2021-12-23T13:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>20,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>145,
#       "name"=>"",
#       "startTime"=>"2021-12-23T13:00:00-06:00",
#       "endTime"=>"2021-12-23T14:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>21,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>146,
#       "name"=>"",
#       "startTime"=>"2021-12-23T14:00:00-06:00",
#       "endTime"=>"2021-12-23T15:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>21,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>147,
#       "name"=>"",
#       "startTime"=>"2021-12-23T15:00:00-06:00",
#       "endTime"=>"2021-12-23T16:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>21,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>148,
#       "name"=>"",
#       "startTime"=>"2021-12-23T16:00:00-06:00",
#       "endTime"=>"2021-12-23T17:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>20,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>149,
#       "name"=>"",
#       "startTime"=>"2021-12-23T17:00:00-06:00",
#       "endTime"=>"2021-12-23T18:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>19,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"W",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=small",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>""},
#      {"number"=>150,
#       "name"=>"",
#       "startTime"=>"2021-12-23T18:00:00-06:00",
#       "endTime"=>"2021-12-23T19:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>18,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"W",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>151,
#       "name"=>"",
#       "startTime"=>"2021-12-23T19:00:00-06:00",
#       "endTime"=>"2021-12-23T20:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>17,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"W",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>152,
#       "name"=>"",
#       "startTime"=>"2021-12-23T20:00:00-06:00",
#       "endTime"=>"2021-12-23T21:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>17,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"SW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=small",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>153,
#       "name"=>"",
#       "startTime"=>"2021-12-23T21:00:00-06:00",
#       "endTime"=>"2021-12-23T22:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>16,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"SSW",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>154,
#       "name"=>"",
#       "startTime"=>"2021-12-23T22:00:00-06:00",
#       "endTime"=>"2021-12-23T23:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>16,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"S",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>155,
#       "name"=>"",
#       "startTime"=>"2021-12-23T23:00:00-06:00",
#       "endTime"=>"2021-12-24T00:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>15,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"SSE",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""},
#      {"number"=>156,
#       "name"=>"",
#       "startTime"=>"2021-12-24T00:00:00-06:00",
#       "endTime"=>"2021-12-24T01:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>15,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"SE",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=small",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>""}]}}






# FORECAST
# % rake white_board:test_ideas
# The lat:44.9673 long:-93.3763 of 1610 Pennsylvania Ave Saint Louis Park
# {"@context"=>
#   ["https://geojson.org/geojson-ld/geojson-context.jsonld",
#    {"@version"=>"1.1",
#     "wx"=>"https://api.weather.gov/ontology#",
#     "geo"=>"http://www.opengis.net/ont/geosparql#",
#     "unit"=>"http://codes.wmo.int/common/unit/",
#     "@vocab"=>"https://api.weather.gov/ontology#"}],
#  "type"=>"Feature",
#  "geometry"=>
#   {"type"=>"Polygon",
#    "coordinates"=>
#     [[[-93.3832362, 44.9877149],
#       [-93.3835967, 44.9663311],
#       [-93.3533824, 44.9660738],
#       [-93.3530152, 44.9874576],
#       [-93.3832362, 44.9877149]]]},
#  "properties"=>
#   {"updated"=>"2021-12-17T15:15:13+00:00",
#    "units"=>"us",
#    "forecastGenerator"=>"BaselineForecastGenerator",
#    "generatedAt"=>"2021-12-17T19:25:28+00:00",
#    "updateTime"=>"2021-12-17T15:15:13+00:00",
#    "validTimes"=>"2021-12-17T09:00:00+00:00/P7DT16H",
#    "elevation"=>{"unitCode"=>"wmoUnit:m", "value"=>274.0152},
#    "periods"=>
#     [{"number"=>1,
#       "name"=>"This Afternoon",
#       "startTime"=>"2021-12-17T13:00:00-06:00",
#       "endTime"=>"2021-12-17T18:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>22,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"ENE",
#       "icon"=>"https://api.weather.gov/icons/land/day/ovc?size=medium",
#       "shortForecast"=>"Cloudy",
#       "detailedForecast"=>
#        "Cloudy, with a high near 22. East northeast wind around 5 mph."},
#      {"number"=>2,
#       "name"=>"Tonight",
#       "startTime"=>"2021-12-17T18:00:00-06:00",
#       "endTime"=>"2021-12-18T06:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>17,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"NNE",
#       "icon"=>
#        "https://api.weather.gov/icons/land/night/ovc/snow,30?size=medium",
#       "shortForecast"=>"Cloudy then Chance Light Snow",
#       "detailedForecast"=>
#        "A chance of snow after 1am. Cloudy, with a low around 17. North northeast wind around 5 mph. Chance of precipitation is 30%."},
#      {"number"=>3,
#       "name"=>"Saturday",
#       "startTime"=>"2021-12-18T06:00:00-06:00",
#       "endTime"=>"2021-12-18T18:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>21,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>"falling",
#       "windSpeed"=>"5 to 10 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/day/snow,20/bkn?size=medium",
#       "shortForecast"=>"Slight Chance Light Snow then Mostly Cloudy",
#       "detailedForecast"=>
#        "A slight chance of snow before 9am. Mostly cloudy. High near 21, with temperatures falling to around 16 in the afternoon. Northwest wind 5 to 10 mph. Chance of precipitation is 20%."},
#      {"number"=>4,
#       "name"=>"Saturday Night",
#       "startTime"=>"2021-12-18T18:00:00-06:00",
#       "endTime"=>"2021-12-19T06:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>8,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"0 to 10 mph",
#       "windDirection"=>"WSW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=medium",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>
#        "Partly cloudy, with a low around 8. West southwest wind 0 to 10 mph."},
#      {"number"=>5,
#       "name"=>"Sunday",
#       "startTime"=>"2021-12-19T06:00:00-06:00",
#       "endTime"=>"2021-12-19T18:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>28,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 to 15 mph",
#       "windDirection"=>"S",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=medium",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>
#        "Partly sunny, with a high near 28. South wind 5 to 15 mph."},
#      {"number"=>6,
#       "name"=>"Sunday Night",
#       "startTime"=>"2021-12-19T18:00:00-06:00",
#       "endTime"=>"2021-12-20T06:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>19,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>"rising",
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"SW",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=medium",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>
#        "Mostly cloudy. Low around 19, with temperatures rising to around 24 overnight. Southwest wind around 10 mph."},
#      {"number"=>7,
#       "name"=>"Monday",
#       "startTime"=>"2021-12-20T06:00:00-06:00",
#       "endTime"=>"2021-12-20T18:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>27,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>"falling",
#       "windSpeed"=>"10 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=medium",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>
#        "Mostly sunny. High near 27, with temperatures falling to around 20 in the afternoon. West northwest wind around 10 mph."},
#      {"number"=>8,
#       "name"=>"Monday Night",
#       "startTime"=>"2021-12-20T18:00:00-06:00",
#       "endTime"=>"2021-12-21T06:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>6,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 to 10 mph",
#       "windDirection"=>"NW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=medium",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>
#        "Partly cloudy, with a low around 6. Northwest wind 5 to 10 mph."},
#      {"number"=>9,
#       "name"=>"Tuesday",
#       "startTime"=>"2021-12-21T06:00:00-06:00",
#       "endTime"=>"2021-12-21T18:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>20,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>"falling",
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WSW",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=medium",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>
#        "Partly sunny. High near 20, with temperatures falling to around 17 in the afternoon. West southwest wind around 5 mph."},
#      {"number"=>10,
#       "name"=>"Tuesday Night",
#       "startTime"=>"2021-12-21T18:00:00-06:00",
#       "endTime"=>"2021-12-22T06:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>10,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"WSW",
#       "icon"=>"https://api.weather.gov/icons/land/night/sct?size=medium",
#       "shortForecast"=>"Partly Cloudy",
#       "detailedForecast"=>
#        "Partly cloudy, with a low around 10. West southwest wind around 5 mph."},
#      {"number"=>11,
#       "name"=>"Wednesday",
#       "startTime"=>"2021-12-22T06:00:00-06:00",
#       "endTime"=>"2021-12-22T18:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>22,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 to 10 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/bkn?size=medium",
#       "shortForecast"=>"Partly Sunny",
#       "detailedForecast"=>
#        "Partly sunny, with a high near 22. West northwest wind 5 to 10 mph."},
#      {"number"=>12,
#       "name"=>"Wednesday Night",
#       "startTime"=>"2021-12-22T18:00:00-06:00",
#       "endTime"=>"2021-12-23T06:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>11,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 to 10 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=medium",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>
#        "Mostly cloudy, with a low around 11. West northwest wind 5 to 10 mph."},
#      {"number"=>13,
#       "name"=>"Thursday",
#       "startTime"=>"2021-12-23T06:00:00-06:00",
#       "endTime"=>"2021-12-23T18:00:00-06:00",
#       "isDaytime"=>true,
#       "temperature"=>23,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 to 10 mph",
#       "windDirection"=>"WNW",
#       "icon"=>"https://api.weather.gov/icons/land/day/sct?size=medium",
#       "shortForecast"=>"Mostly Sunny",
#       "detailedForecast"=>
#        "Mostly sunny, with a high near 23. West northwest wind 5 to 10 mph."},
#      {"number"=>14,
#       "name"=>"Thursday Night",
#       "startTime"=>"2021-12-23T18:00:00-06:00",
#       "endTime"=>"2021-12-24T06:00:00-06:00",
#       "isDaytime"=>false,
#       "temperature"=>11,
#       "temperatureUnit"=>"F",
#       "temperatureTrend"=>nil,
#       "windSpeed"=>"5 mph",
#       "windDirection"=>"SSW",
#       "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=medium",
#       "shortForecast"=>"Mostly Cloudy",
#       "detailedForecast"=>
#        "Mostly cloudy, with a low around 11. South southwest wind around 5 mph."}]}}
