
AllCops:
  NewCops: enable
  Exclude:
    - 'spec/**/*.rb'
    - 'db/schema.rb'
    - 'bin/bundle'

Layout/LineLength:
  Max: 180

Metrics/MethodLength:
  Max: 50
# reduce to 40, then 30
Metrics/BlockLength:
  Max: 30

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false  # six of one, a half-dozen of the other

Style/Documentation:
  Enabled: false

Style/FormatString:
  Enabled: false
