 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/postal_code_forecasts", type: :request do
  
  # PostalCodeForecast. As you add validations to PostalCodeForecast, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PostalCodeForecast.create! valid_attributes
      get postal_code_forecasts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      postal_code_forecast = PostalCodeForecast.create! valid_attributes
      get postal_code_forecast_url(postal_code_forecast)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_postal_code_forecast_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      postal_code_forecast = PostalCodeForecast.create! valid_attributes
      get edit_postal_code_forecast_url(postal_code_forecast)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PostalCodeForecast" do
        expect {
          post postal_code_forecasts_url, params: { postal_code_forecast: valid_attributes }
        }.to change(PostalCodeForecast, :count).by(1)
      end

      it "redirects to the created postal_code_forecast" do
        post postal_code_forecasts_url, params: { postal_code_forecast: valid_attributes }
        expect(response).to redirect_to(postal_code_forecast_url(PostalCodeForecast.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PostalCodeForecast" do
        expect {
          post postal_code_forecasts_url, params: { postal_code_forecast: invalid_attributes }
        }.to change(PostalCodeForecast, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post postal_code_forecasts_url, params: { postal_code_forecast: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested postal_code_forecast" do
        postal_code_forecast = PostalCodeForecast.create! valid_attributes
        patch postal_code_forecast_url(postal_code_forecast), params: { postal_code_forecast: new_attributes }
        postal_code_forecast.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the postal_code_forecast" do
        postal_code_forecast = PostalCodeForecast.create! valid_attributes
        patch postal_code_forecast_url(postal_code_forecast), params: { postal_code_forecast: new_attributes }
        postal_code_forecast.reload
        expect(response).to redirect_to(postal_code_forecast_url(postal_code_forecast))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        postal_code_forecast = PostalCodeForecast.create! valid_attributes
        patch postal_code_forecast_url(postal_code_forecast), params: { postal_code_forecast: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested postal_code_forecast" do
      postal_code_forecast = PostalCodeForecast.create! valid_attributes
      expect {
        delete postal_code_forecast_url(postal_code_forecast)
      }.to change(PostalCodeForecast, :count).by(-1)
    end

    it "redirects to the postal_code_forecasts list" do
      postal_code_forecast = PostalCodeForecast.create! valid_attributes
      delete postal_code_forecast_url(postal_code_forecast)
      expect(response).to redirect_to(postal_code_forecasts_url)
    end
  end
end
